defaults: vlm_sft-nemotron-omni-30ba3b-clevr-1n8g-megatron-tp4etp4-energon.v1.yaml
sft:
  max_num_steps: 500
policy:
  max_total_sequence_length: 65536
  train_global_batch_size: 2
  megatron_cfg:
    context_parallel_size: 2
checkpointing:
  enabled: true
  save_period: 5
  save_optimizer: false
logger:
  log_dir: logs/sft-nemotron-omni-30ba3b-65k-ckptresume
  tensorboard:
    log_dir: tb_logs-sft-nemotron-omni-30ba3b-65k-ckptresume
cluster:
  num_nodes: 2
