defaults: ../../sft_vlm_3B.yaml
sft:
  max_num_steps: 1000
  val_period: 20
policy:
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    apply_rope_fusion: false
    distributed_data_parallel_config:
      overlap_grad_reduce: false
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  optimizer: null
logger:
  wandb_enabled: true
