defaults: sft-super67b-generalist.n16dss.yaml
policy:
  train_global_batch_size: 4
  megatron_cfg:
    tensor_model_parallel_size: 8
    context_parallel_size: 8
cluster:
  gpus_per_node: 4
  num_nodes: 32
checkpointing:
  checkpoint_dir: /data/nemorl-runs/sft-super67b-n32-dss-generalist
