defaults: sft-super67b-generalist.n64dss.yaml
policy:
  train_global_batch_size: 16
cluster:
  num_nodes: 128
logger:
  log_dir: logs/sft-super67b-n128-dss-generalist
  wandb:
    name: sft-super67b-n128-dss-generalist
  tensorboard:
    log_dir: logs/sft-super67b-n128-dss-generalist
checkpointing:
  checkpoint_dir: /data/nemorl-runs/sft-super67b-n128-dss-generalist
