#!/usr/bin/env bash
# Smoke-test launcher for the polygon_naming multi-turn multimodal recipe
# on a single interactive allocation (2 nodes × 8 GPUs). Mirrors
# run_gymv_smoke.sh but points at polygon_naming + multimodal_simple_agent.
# Run this from INSIDE the NeMo-RL container, WD = /opt/nemo-rl.
#
# Usage:
#   examples/nemo_gym/run_polygon_naming_smoke.sh                     # sync GRPO
#   examples/nemo_gym/run_polygon_naming_smoke.sh wandb                # + wandb logging
#   examples/nemo_gym/run_polygon_naming_smoke.sh grpo.max_num_steps=1 # Hydra overrides
#
# The dataset JSONLs must exist under
#   3rdparty/Gym-workspace/Gym/resources_servers/polygon_naming/data/{train,validation}.jsonl
# Auto-generated by this script if missing (see generate_polygon_naming_data.sh
# for a standalone regenerator).

set -euo pipefail

# -- Optional "wandb" token --------------------------------------------------
EXTRA_HYDRA_ARGS=()
if [[ "${1:-}" == "wandb" ]]; then
    EXTRA_HYDRA_ARGS+=("logger.wandb_enabled=true")
    shift
fi

RECIPE="examples/nemo_gym/grpo_nemotron_omni_30ba3b_polygon_naming_smoke.yaml"
ENTRY="examples/nemo_gym/run_multimodal_grpo_nemo_gym.py"

if [[ ! -f "${RECIPE}" ]]; then
    echo "error: recipe not found at ${RECIPE}" >&2
    exit 1
fi

# HF token — needed for gated Nemotron-Omni downloads.
if [[ -z "${HF_TOKEN:-}" ]]; then
    echo "warn: HF_TOKEN unset — HF hub downloads may 401" >&2
fi

# Shared caches on Lustre workspace, not container rootfs.
export HF_HOME="${HF_HOME:-${PWD}/.cache/huggingface}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/hub}"

# Ray AF_UNIX socket path cap on Linux (107 bytes).
export RAY_TMPDIR="${RAY_TMPDIR:-/tmp/ray}"
mkdir -p "${RAY_TMPDIR}"

# -- Auto-generate train/validation JSONLs if missing ---------------------
GYM_DATA_DIR="3rdparty/Gym-workspace/Gym/resources_servers/polygon_naming/data"
TRAIN_JSONL="${GYM_DATA_DIR}/train.jsonl"
VALIDATION_JSONL="${GYM_DATA_DIR}/validation.jsonl"

if [[ ! -f "${TRAIN_JSONL}" || ! -f "${VALIDATION_JSONL}" ]]; then
    echo "==> polygon_naming JSONLs missing — auto-generating"
    examples/nemo_gym/generate_polygon_naming_data.sh
fi

echo "==> recipe: ${RECIPE}"
echo "==> entry:  ${ENTRY}"
echo "==> train:  ${TRAIN_JSONL} ($(wc -l < "${TRAIN_JSONL}") rows)"
echo "==> val:    ${VALIDATION_JSONL} ($(wc -l < "${VALIDATION_JSONL}") rows)"
echo "==> HF_HOME=${HF_HOME}"
echo "==> RAY_TMPDIR=${RAY_TMPDIR}"
if [[ "${#EXTRA_HYDRA_ARGS[@]}" -gt 0 ]]; then
    echo "==> extra:  ${EXTRA_HYDRA_ARGS[*]}"
fi

exec uv run --locked --no-sync \
    "${ENTRY}" \
    --config "${RECIPE}" \
    ${EXTRA_HYDRA_ARGS[@]+"${EXTRA_HYDRA_ARGS[@]}"} \
    "$@"
