# GRPO Algorithm Configuration
defaults: "grpo_clevr_cogent_trainA.yaml"

policy:
  model_name: "Qwen/Qwen2-VL-7B-Instruct"
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 0
    activation_checkpointing: false
    converter_type: "Qwen2_VLForConditionalGeneration"
    tensor_model_parallel_size: 4
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    sequence_parallel: false
    freeze_moe_router: true
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none" # "seq_aux_loss" causes logprob error divergence for grpo
    moe_router_bias_update_rate: 0.0 # by default, disable bias updates for grpo
    #gives ~20% training perf speedup with sequence packing 
    apply_rope_fusion: True

  dtensor_cfg:
    enabled: false
  
cluster:
  gpus_per_node: 8