defaults:
  - sft_vlm_3B_megatron.yaml

checkpointing:
  enabled: true
  checkpoint_dir: results/sft_${policy.model_name}_clevr_energon
  metric_name: val:val_loss
  higher_is_better: false
  keep_top_k: 1
  save_period: 10

data:
  _override_: true
  backend: energon
  max_input_seq_length: ${policy.max_total_sequence_length}
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  shuffle: true
  num_workers: 0
  energon:
    num_workers: 8
    shuffle_buffer_size: 1000
    processor_adapter: hf_multimodal
  train:
    path: /data/nemorl-datasets/clevr
    split: train
    virtual_epoch_length: 4375
  validation:
    path: /data/nemorl-datasets/clevr
    split: valA
    limit: 5000

logger:
  log_dir: logs/sft-qwen2.5-vl-3b-clevr-energon
  wandb_enabled: true
  tensorboard_enabled: true
  monitor_gpus: true
  wandb:
    project: sft-dev
    name: sft-qwen2.5-vl-3b-clevr-energon
  tensorboard:
    log_dir: tb_logs-sft-qwen2.5-vl-3b-clevr-energon
  swanlab:
    name: sft-qwen2.5-vl-3b-clevr-energon
  mlflow:
    run_name: sft-qwen2.5-vl-3b-clevr-energon
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
